en_questions = [
    "Describe a time when you took on a leadership role unexpectedly.",
    "Tell me about a time you took ownership of a challenging project.",
    "How have you dealt with taking responsibility for a project that was initially headed for failure?",
    "Describe a time when you had to make a tough decision quickly.",
    "Give an example of a project where you went above and beyond your responsibilities.",
    "Explain how you've prioritized competing goals when leading a team.",
    "How do you motivate yourself and others?",
    "Tell me about a time you had to change your leadership approach based on team feedback.",
    "Describe a time when you convinced someone of your idea despite initial resistance.",
    "What’s an example of when you assumed a role or responsibility that others were hesitant to take on?",
    "Describe a time when you had to solve a difficult problem.",
    "Give an example of how you approached solving a problem when you didn't have all the information.",
    "Tell me about a time when you solved a problem creatively.",
    "How did you handle a problem where you had conflicting input from different stakeholders?",
    "Describe a time when you identified a critical problem nobody else had noticed.",
    "Explain how you’ve handled a complex problem under time constraints.",
    "How do you approach troubleshooting when there’s no obvious solution?",
    "Describe a time you had to pivot your solution after realizing it wasn’t feasible.",
    "Give an example of how you've solved a problem differently than most people would.",
    "Tell me about a time you changed your approach to a problem based on new insights.",
    "Describe a time when you had to explain a complex issue to someone without technical expertise.",
    "Give an example of when you persuaded someone to see things from your perspective.",
    "How have you handled giving difficult feedback to a teammate?",
    "Describe a time when you had to present to a difficult audience.",
    "Tell me about a time when clear communication was critical to a project’s success.",
    "How have you handled miscommunication that led to a misunderstanding?",
    "Describe a time when you had to negotiate or manage expectations.",
    "How do you approach making a point when others disagree?",
    "Give an example of how you’ve adjusted your communication for different stakeholders.",
    "Tell me about a time when you advocated for your team or project.",
    "Describe a time when you proposed an innovative solution that others hadn’t considered.",
    "Tell me about a time when you identified a new way to improve a process.",
    "Explain a situation where you solved a problem in a unique or unexpected way.",
    "Describe a time when you led a project with a high level of creativity.",
    "How do you encourage innovative thinking in a team?",
    "Describe an example of when you took a calculated risk to innovate.",
    "Give an example of when you generated new ideas to improve team performance.",
    "How have you handled an idea you were passionate about that others did not support?",
    "Tell me about a creative solution you devised under tight constraints.",
    "How do you prioritize innovation within the scope of your projects?",
    "Describe a time when you had to adapt to a major change in a project.",
    "Tell me about a situation where you had to change your approach due to unforeseen challenges.",
    "How did you manage stress in a high-stakes or high-pressure situation?",
    "Describe a time when a project didn’t go as planned and how you handled it.",
    "Give an example of when you had to learn a new skill quickly.",
    "How do you handle unexpected failures or setbacks?",
    "Describe a time when you received negative feedback and how you reacted.",
    "Tell me about a time you had to persist through a particularly challenging situation.",
    "Give an example of when you had to adapt to a sudden change in team dynamics.",
    "How have you balanced staying calm and productive during a challenging period?",
    "Describe a time when you had to work with a difficult team member.",
    "How have you contributed to building a collaborative environment within a team?",
    "Tell me about a time when you helped resolve a team conflict.",
    "Describe an example of when you supported a team member who was struggling.",
    "How have you handled disagreements within a team setting?",
    "Tell me about a time when you had to share credit with others on a team.",
    "Give an example of how you kept a team motivated and on track.",
    "Describe a time when you had to rely on others to complete a project.",
    "How have you balanced your strengths with those of a team to accomplish a goal?",
    "Tell me about a time when you adapted to someone else’s working style.",
    "Describe a time when you made a decision based on customer feedback.",
    "How have you handled managing expectations with different stakeholders?",
    "Tell me about a time when you exceeded a customer’s or stakeholder’s expectations.",
    "Describe a situation where you advocated for the customer’s perspective.",
    "Give an example of when you had to say 'no' to a stakeholder and how you handled it.",
    "How do you balance customer needs with business priorities?",
    "Tell me about a time you handled a difficult request from a client or stakeholder.",
    "Describe a time when customer feedback led to a change in your work.",
    "How have you managed to deliver value when dealing with tight constraints?",
    "Give an example of how you ensured stakeholder alignment on a project.",
    "Describe a time when you took a significant step to improve a skill.",
    "How do you seek out new learning opportunities?",
    "Tell me about a project where you applied a new skill or technology.",
    "Give an example of a time you learned something from a mistake.",
    "How do you prioritize self-improvement with your work responsibilities?",
    "Describe a time when you were proactive in seeking feedback.",
    "Tell me about a time when you learned from someone you managed.",
    "Describe an instance where a mentor or peer helped you grow.",
    "Explain a time when you took initiative to solve a skills gap.",
    "How do you ensure you stay updated in your field?",
    "Describe a time when you had to manage competing priorities.",
    "Tell me about a time when you worked under a strict deadline.",
    "How do you handle project setbacks or delays?",
    "Describe a time when your planning prevented a project from falling behind.",
    "How have you managed time across multiple projects?",
    "Give an example of a project where your organizational skills were essential.",
    "Describe a time when you had to pivot your plan halfway through a project.",
    "How do you set realistic timelines and milestones?",
    "Tell me about a time when you missed a deadline and how you managed it.",
    "Explain a situation where time management was critical to project success.",
    "Describe a time when you helped promote an inclusive environment.",
    "Tell me about a time you resolved a misunderstanding related to cultural differences.",
    "How do you ensure everyone on your team feels heard?",
    "Describe a time when you advocated for someone with a different background.",
    "Give an example of when you adjusted your behavior to support inclusivity.",
    "How have you handled biased or unfair situations in the workplace?",
    "Tell me about a time when diversity added value to your project.",
    "Describe an instance where you went out of your way to support a teammate from a different background.",
    "How do you encourage open discussions around diversity in your team?",
    "Give an example of how you helped a team become more inclusive.",
]

en_questions_short = [
    "Give an example of a time you learned something from a mistake.",
    "Give an example of a project where you went above and beyond your responsibilities.",
    "Describe a time when you convinced someone of your idea despite initial resistance.",
]

pt_questions = [
    "Descreva uma vez em que você assumiu uma posição de liderança inesperadamente.",
    "Conte-me sobre uma vez em que você assumiu a responsabilidade por um projeto desafiador.",
    "Como você lidou com a responsabilidade de um projeto que inicialmente estava indo para o fracasso?",
    "Descreva uma vez em que você teve que tomar uma decisão difícil rapidamente.",
    "Dê um exemplo de um projeto onde você foi além das suas responsabilidades.",
    "Explique como você priorizou objetivos concorrentes ao liderar uma equipe.",
    "Como você se motiva e motiva os outros?",
    "Conte-me sobre uma vez em que você teve que mudar sua abordagem de liderança com base no feedback da equipe.",
    "Descreva uma vez em que você convenceu alguém sobre sua ideia, apesar da resistência inicial.",
    "Qual é um exemplo de quando você assumiu uma função ou responsabilidade que os outros estavam hesitantes em assumir?",
    "Descreva uma vez em que você teve que resolver um problema difícil.",
    "Dê um exemplo de como você abordou a resolução de um problema quando não tinha todas as informações.",
    "Conte-me sobre uma vez em que você resolveu um problema de forma criativa.",
    "Como você lidou com um problema onde recebeu contribuições conflitantes de diferentes partes interessadas?",
    "Descreva uma vez em que você identificou um problema crítico que ninguém mais havia notado.",
    "Explique como você lidou com um problema complexo sob restrições de tempo.",
    "Como você aborda a resolução de problemas quando não há uma solução óbvia?",
    "Descreva uma vez em que você teve que mudar sua solução depois de perceber que ela não era viável.",
    "Dê um exemplo de como você resolveu um problema de maneira diferente da maioria das pessoas.",
    "Conte-me sobre uma vez em que você mudou sua abordagem para um problema com base em novos insights.",
    "Descreva uma vez em que você teve que explicar um problema complexo para alguém sem conhecimento técnico.",
    "Dê um exemplo de quando você persuadiu alguém a ver as coisas sob sua perspectiva.",
    "Como você lidou ao dar um feedback difícil para um colega de equipe?",
    "Descreva uma vez em que você teve que se apresentar para um público difícil.",
    "Conte-me sobre uma vez em que uma comunicação clara foi crucial para o sucesso de um projeto.",
    "Como você lidou com uma falha de comunicação que levou a um mal-entendido?",
    "Descreva uma vez em que você teve que negociar ou gerenciar expectativas.",
    "Como você aborda fazer um ponto quando outros discordam?",
    "Dê um exemplo de como você ajustou sua comunicação para diferentes partes interessadas.",
    "Conte-me sobre uma vez em que você defendeu sua equipe ou projeto.",
    "Descreva uma vez em que você propôs uma solução inovadora que os outros não haviam considerado.",
    "Conte-me sobre uma vez em que você identificou uma nova maneira de melhorar um processo.",
    "Explique uma situação em que você resolveu um problema de uma maneira única ou inesperada.",
    "Descreva uma vez em que você liderou um projeto com um alto nível de criatividade.",
    "Como você incentiva o pensamento inovador em uma equipe?",
    "Descreva um exemplo de quando você assumiu um risco calculado para inovar.",
    "Dê um exemplo de quando você gerou novas ideias para melhorar o desempenho da equipe.",
    "Como você lidou com uma ideia pela qual era apaixonado, mas que os outros não apoiaram?",
    "Conte-me sobre uma solução criativa que você criou sob restrições apertadas.",
    "Como você prioriza a inovação dentro do escopo dos seus projetos?",
    "Descreva uma vez em que você teve que se adaptar a uma mudança significativa em um projeto.",
    "Conte-me sobre uma situação em que você teve que mudar sua abordagem devido a desafios imprevistos.",
    "Como você gerenciou o estresse em uma situação de alto risco ou alta pressão?",
    "Descreva uma vez em que um projeto não saiu como planejado e como você lidou com isso.",
    "Dê um exemplo de quando você teve que aprender uma nova habilidade rapidamente.",
    "Como você lida com falhas ou contratempos inesperados?",
    "Descreva uma vez em que você recebeu um feedback negativo e como reagiu.",
    "Conte-me sobre uma vez em que você teve que persistir através de uma situação particularmente desafiadora.",
    "Dê um exemplo de quando você teve que se adaptar a uma mudança repentina na dinâmica da equipe.",
    "Como você equilibra ficar calmo e produtivo durante um período desafiador?",
    "Descreva uma vez em que você teve que trabalhar com um colega de equipe difícil.",
    "Como você contribuiu para construir um ambiente colaborativo dentro de uma equipe?",
    "Conte-me sobre uma vez em que você ajudou a resolver um conflito na equipe.",
    "Descreva um exemplo de quando você apoiou um membro da equipe que estava tendo dificuldades.",
    "Como você lidou com desentendimentos dentro de um ambiente de equipe?",
    "Conte-me sobre uma vez em que você teve que compartilhar o crédito com os outros em uma equipe.",
    "Dê um exemplo de como você manteve a equipe motivada e no caminho certo.",
    "Descreva uma vez em que você teve que contar com os outros para concluir um projeto.",
    "Como você equilibrou suas forças com as de uma equipe para alcançar um objetivo?",
    "Conte-me sobre uma vez em que você se adaptou ao estilo de trabalho de outra pessoa.",
    "Descreva uma vez em que você tomou uma decisão com base no feedback de um cliente.",
    "Como você lidou com a gestão de expectativas com diferentes partes interessadas?",
    "Conte-me sobre uma vez em que você superou as expectativas de um cliente ou parte interessada.",
    "Descreva uma situação em que você defendeu a perspectiva do cliente.",
    "Dê um exemplo de quando você teve que dizer 'não' a uma parte interessada e como lidou com isso.",
    "Como você equilibra as necessidades do cliente com as prioridades de negócios?",
    "Conte-me sobre uma vez em que você lidou com uma solicitação difícil de um cliente ou parte interessada.",
    "Descreva uma vez em que o feedback do cliente levou a uma mudança no seu trabalho.",
    "Como você conseguiu entregar valor ao lidar com restrições apertadas?",
    "Dê um exemplo de como você garantiu o alinhamento das partes interessadas em um projeto.",
    "Descreva uma vez em que você deu um passo significativo para melhorar uma habilidade.",
    "Como você busca novas oportunidades de aprendizado?",
    "Conte-me sobre um projeto em que você aplicou uma nova habilidade ou tecnologia.",
    "Dê um exemplo de uma vez em que você aprendeu algo com um erro.",
    "Como você prioriza o autoaperfeiçoamento com suas responsabilidades de trabalho?",
    "Descreva uma vez em que você foi proativo ao buscar feedback.",
    "Conte-me sobre uma vez em que você aprendeu com alguém que você gerenciava.",
    "Descreva uma situação onde um mentor ou colega ajudou você a crescer.",
    "Explique uma vez em que você tomou a iniciativa de resolver uma lacuna de habilidades.",
    "Como você garante que continua atualizado na sua área?",
    "Descreva uma vez em que você teve que gerenciar prioridades concorrentes.",
    "Conte-me sobre uma vez em que você trabalhou sob um prazo apertado.",
    "Como você lida com contratempos ou atrasos de projetos?",
    "Descreva uma vez em que seu planejamento evitou que um projeto ficasse para trás.",
    "Como você gerenciou o tempo entre múltiplos projetos?",
    "Dê um exemplo de um projeto onde suas habilidades organizacionais foram essenciais.",
    "Descreva uma vez em que você teve que mudar seu plano no meio de um projeto.",
    "Como você define prazos e marcos realistas?",
    "Conte-me sobre uma vez em que você perdeu um prazo e como lidou com isso.",
    "Explique uma situação onde o gerenciamento de tempo foi crítico para o sucesso do projeto.",
    "Descreva uma vez em que você ajudou a promover um ambiente inclusivo.",
    "Conte-me sobre uma vez em que você resolveu um mal-entendido relacionado a diferenças culturais.",
    "Como você garante que todos na sua equipe se sintam ouvidos?",
    "Descreva uma vez em que você defendeu alguém com um background diferente.",
    "Dê um exemplo de quando você ajustou seu comportamento para apoiar a inclusão.",
    "Como você lidou com situações tendenciosas ou injustas no ambiente de trabalho?",
    "Conte-me sobre uma vez em que a diversidade agregou valor ao seu projeto.",
    "Descreva uma situação em que você se esforçou para apoiar um colega de equipe de um background diferente.",
    "Como você incentiva discussões abertas sobre diversidade em sua equipe?",
    "Dê um exemplo de como você ajudou uma equipe a se tornar mais inclusiva.",
]


pt_questions_short = [
    "Dê um exemplo de uma vez em que você aprendeu algo com um erro.",
    "Dê um exemplo de um projeto em que você foi além das suas responsabilidades",
    "Descreva uma vez em que você convenceu alguém sobre sua ideia, apesar da resistência inicial.",
]

it_questions = [
    "Descrivi una volta in cui hai assunto un ruolo di leadership inaspettatamente.",
    "Raccontami di una volta in cui hai preso in carico un progetto impegnativo.",
    "Come hai gestito la responsabilità di un progetto che inizialmente stava per fallire?",
    "Descrivi una volta in cui hai dovuto prendere una decisione difficile rapidamente.",
    "Fornisci un esempio di un progetto in cui hai superato le tue responsabilità.",
    "Spiega come hai prioritizzato obiettivi in competizione quando hai guidato un team.",
    "Come ti motivi e motivi gli altri?",
    "Raccontami di una volta in cui hai dovuto cambiare il tuo approccio alla leadership in base al feedback del team.",
    "Descrivi una volta in cui hai convinto qualcuno della tua idea nonostante una resistenza iniziale.",
    "Qual è un esempio di quando hai assunto un ruolo o responsabilità che altri esitavano ad assumere?",
    "Descrivi una volta in cui hai dovuto risolvere un problema difficile.",
    "Fornisci un esempio di come hai affrontato la risoluzione di un problema quando non avevi tutte le informazioni.",
    "Raccontami di una volta in cui hai risolto un problema in modo creativo.",
    "Come hai gestito un problema in cui avevi input contrastanti da parte di diversi stakeholder?",
    "Descrivi una volta in cui hai identificato un problema critico che nessun altro aveva notato.",
    "Spiega come hai gestito un problema complesso sotto vincoli di tempo.",
    "Come affronti il troubleshooting quando non c'è una soluzione ovvia?",
    "Descrivi una volta in cui hai dovuto adattare la tua soluzione dopo aver capito che non era fattibile.",
    "Fornisci un esempio di come hai risolto un problema in modo diverso rispetto alla maggior parte delle persone.",
    "Raccontami di una volta in cui hai cambiato il tuo approccio a un problema sulla base di nuove intuizioni.",
    "Descrivi una volta in cui hai dovuto spiegare un problema complesso a qualcuno senza competenze tecniche.",
    "Fornisci un esempio di quando hai convinto qualcuno a vedere le cose dal tuo punto di vista.",
    "Come hai gestito il dare feedback difficili a un membro del team?",
    "Descrivi una volta in cui hai dovuto presentare a un pubblico difficile.",
    "Raccontami di una volta in cui una comunicazione chiara è stata cruciale per il successo di un progetto.",
    "Come hai gestito una comunicazione errata che ha portato a un malinteso?",
    "Descrivi una volta in cui hai dovuto negoziare o gestire le aspettative.",
    "Come affronti fare un punto quando altri sono in disaccordo?",
    "Fornisci un esempio di come hai adattato la tua comunicazione per diversi stakeholder.",
    "Raccontami di una volta in cui hai difeso il tuo team o progetto.",
    "Descrivi una volta in cui hai proposto una soluzione innovativa che altri non avevano considerato.",
    "Raccontami di una volta in cui hai identificato un nuovo modo per migliorare un processo.",
    "Spiega una situazione in cui hai risolto un problema in modo unico o inaspettato.",
    "Descrivi una volta in cui hai guidato un progetto con un alto livello di creatività.",
    "Come incoraggi il pensiero innovativo in un team?",
    "Descrivi un esempio di quando hai preso un rischio calcolato per innovare.",
    "Fornisci un esempio di quando hai generato nuove idee per migliorare le prestazioni del team.",
    "Come hai gestito un'idea a cui tenevi ma che gli altri non supportavano?",
    "Raccontami di una soluzione creativa che hai ideato sotto vincoli stretti.",
    "Come prioritizzi l'innovazione nel contesto dei tuoi progetti?",
    "Descrivi una volta in cui hai dovuto adattarti a un cambiamento importante in un progetto.",
    "Raccontami di una situazione in cui hai dovuto cambiare il tuo approccio a causa di sfide impreviste.",
    "Come hai gestito lo stress in una situazione ad alta posta o ad alta pressione?",
    "Descrivi una volta in cui un progetto non è andato come previsto e come l'hai gestito.",
    "Fornisci un esempio di quando hai dovuto imparare rapidamente una nuova competenza.",
    "Come gestisci i fallimenti o gli ostacoli imprevisti?",
    "Descrivi una volta in cui hai ricevuto feedback negativo e come hai reagito.",
    "Raccontami di una volta in cui hai dovuto perseverare in una situazione particolarmente difficile.",
    "Fornisci un esempio di quando hai dovuto adattarti a un cambiamento improvviso nella dinamica del team.",
    "Come hai bilanciato restare calmo e produttivo durante un periodo difficile?",
    "Descrivi una volta in cui hai dovuto lavorare con un membro del team difficile.",
    "Come hai contribuito a costruire un ambiente collaborativo all'interno di un team?",
    "Raccontami di una volta in cui hai aiutato a risolvere un conflitto all'interno del team.",
    "Descrivi un esempio di quando hai supportato un membro del team che stava avendo difficoltà.",
    "Come hai gestito i disaccordi all'interno di un ambiente di team?",
    "Raccontami di una volta in cui hai dovuto condividere il merito con gli altri in un team.",
    "Fornisci un esempio di come hai mantenuto il team motivato e in carreggiata.",
    "Descrivi una volta in cui hai dovuto fare affidamento sugli altri per completare un progetto.",
    "Come hai bilanciato i tuoi punti di forza con quelli di un team per raggiungere un obiettivo?",
    "Raccontami di una volta in cui ti sei adattato allo stile di lavoro di qualcun altro.",
    "Descrivi una volta in cui hai preso una decisione basata sul feedback del cliente.",
    "Come hai gestito la gestione delle aspettative con diversi stakeholder?",
    "Raccontami di una volta in cui hai superato le aspettative di un cliente o di uno stakeholder.",
    "Descrivi una situazione in cui hai difeso la prospettiva del cliente.",
    "Fornisci un esempio di quando hai dovuto dire 'no' a uno stakeholder e come l'hai gestito.",
    "Come bilanci le esigenze del cliente con le priorità aziendali?",
    "Raccontami di una volta in cui hai gestito una richiesta difficile da un cliente o stakeholder.",
    "Descrivi una volta in cui il feedback del cliente ha portato a un cambiamento nel tuo lavoro.",
    "Come sei riuscito a fornire valore quando hai avuto vincoli stretti?",
    "Fornisci un esempio di come hai garantito l'allineamento degli stakeholder su un progetto.",
    "Descrivi una volta in cui hai fatto un passo significativo per migliorare una competenza.",
    "Come cerchi nuove opportunità di apprendimento?",
    "Raccontami di un progetto in cui hai applicato una nuova competenza o tecnologia.",
    "Fornisci un esempio di una volta in cui hai imparato qualcosa da un errore.",
    "Come prioritizzi il miglioramento di te stesso con le tue responsabilità lavorative?",
    "Descrivi una volta in cui sei stato proattivo nel cercare feedback.",
    "Raccontami di una volta in cui hai imparato da qualcuno che gestivi.",
    "Descrivi un episodio in cui un mentore o un collega ti ha aiutato a crescere.",
    "Spiega una volta in cui hai preso l'iniziativa per risolvere una lacuna nelle competenze.",
    "Come fai per assicurarti di rimanere aggiornato nel tuo campo?",
    "Descrivi una volta in cui hai dovuto gestire priorità concorrenti.",
    "Raccontami di una volta in cui hai lavorato sotto una scadenza severa.",
    "Come gestisci i ritardi o gli imprevisti nei progetti?",
    "Descrivi una volta in cui la tua pianificazione ha evitato che un progetto ritardasse.",
    "Come hai gestito il tempo su più progetti?",
    "Fornisci un esempio di un progetto in cui le tue competenze organizzative sono state essenziali.",
    "Descrivi una volta in cui hai dovuto adattare il tuo piano a metà di un progetto.",
    "Come stabilisci tempistiche e milestone realistici?",
    "Raccontami di una volta in cui hai mancato una scadenza e come l'hai gestita.",
    "Spiega una situazione in cui la gestione del tempo è stata critica per il successo del progetto.",
    "Descrivi una volta in cui hai aiutato a promuovere un ambiente inclusivo.",
    "Raccontami di una volta in cui hai risolto un malinteso legato a differenze culturali.",
    "Come fai per garantire che tutti nel tuo team si sentano ascoltati?",
    "Descrivi una volta in cui hai difeso qualcuno con un background diverso.",
    "Fornisci un esempio di quando hai adattato il tuo comportamento per supportare l'inclusività.",
    "Come hai gestito situazioni di pregiudizio o ingiustizia sul posto di lavoro?",
    "Raccontami di una volta in cui la diversità ha aggiunto valore al tuo progetto.",
    "Descrivi un episodio in cui ti sei impegnato a supportare un compagno di squadra con un background diverso.",
    "Come incoraggi discussioni aperte sulla diversità nel tuo team?",
    "Fornisci un esempio di come hai aiutato un team a diventare più inclusivo.",
]


it_questions_short = [
    "Fornisci un esempio di una volta in cui hai imparato qualcosa da un errore.",
    "Fornisci un esempio di un progetto in cui hai superato le tue responsabilità.",
    "Descrivi una volta in cui hai convinto qualcuno della tua idea nonostante una resistenza iniziale.",
]
