FROM rust:1.93-alpine AS builder

WORKDIR /app

COPY Cargo.toml Cargo.lock start.sh ./

RUN mkdir -p src && echo '' > src/lib.rs

RUN cargo fetch

# Remove the temporary file before copying the actual source code
RUN rm -rf src

# Copy the actual source code separately
COPY src ./src

RUN cargo build --release

# Stage 2: Runtime Stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/target/release/lord_ferris_rs ./lord_ferris_rs
COPY --from=builder /app/start.sh ./start.sh

RUN chmod +x /app/start.sh

ENTRYPOINT ["/app/start.sh"]
